{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas | default 1 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "kargo.selectorLabels" . | nindent 6 }}
      {{- include "kargo.api.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kargo.selectorLabels" . | nindent 8 }}
        {{- include "kargo.api.labels" . | nindent 8 }}
      annotations:
        configmap/checksum: {{ include (print $.Template.BasePath "/api/configmap.yaml") . | sha256sum }}
        secret/checksum: {{ include (print $.Template.BasePath "/api/secret.yaml") . | sha256sum }}
    spec:
      serviceAccount: kargo-api
      containers:
        - name: api
          image: {{ include "kargo.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/kargo", "api"]
          envFrom:
            - configMapRef:
                name: kargo-api
            - secretRef:
                name: kargo-api
          ports:
            - name: h2c
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            exec:
              command: ["/usr/local/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 5
          resources: {{ toYaml .Values.api.resources }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
